
services:
  backend1:
    build:
      context: ./backend
    container_name: backend1
    expose:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/app_db
    depends_on:
      - postgres
      - redis

  backend2:
    build:
      context: ./backend
    container_name: backend2
    expose:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/app_db
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - nginx

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"  # ← Port externe 5433 → port interne 5432
      # apres
      # docker-compose down
      # docker-compose up --build

    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis    

volumes:
  pgdata:
