global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-microservices'
    static_configs:
      - targets:
          - 'client:8000'
          - 'commande:8000'
          - 'panier:8000'
          - 'produits:8000'
          - 'rapport:8000'
          - 'stock1:8000'
          - 'stock2:8000'
          - 'utilisateurs:8000'
          - 'ventes:8000'
