[tool.ruff]
# Longueur maximale des lignes
line-length = 100

# Version cible de Python (à adapter si tu utilises Python 3.10, 3.8, etc.)
target-version = "py311"

# Dossiers à ignorer pendant le linting
extend-exclude = [
    "__pycache__",
    ".venv",
    "migrations",
    "tests/__pycache__",
    "tests/data/"
]

# Codes de règles activées
lint.select = ["E", "F", "W", "I"]
lint.ignore = ["E501"]
